apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cfmtls-issuer.serviceAccountName" . }}
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cfmtls-issuer.fullname" . }}-role
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
rules:
  # Permissions for CertificateRequests and CertificateSigningRequests
  - apiGroups: ["cert-manager.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["list", "watch", "create", "get", "update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["list", "watch", "get", "update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/finalizers"]
    verbs: ["list", "watch", "create", "get", "update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/conditions"]
    verbs: ["update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["signers"]
    verbs: ["approve"] # added this permission!
    resourceNames: ["cfmtlsclusterissuers.cfmtls.cert.manager.io/*"] # Added only for this resource name
  - apiGroups: ["cert-manager.io"]
    resources: ["signers"]
    verbs: ["approve"] # added this permission!
    resourceNames: ["cfmtlsissuers.cfmtls.cert.manager.io/*"] # Added only for this resource name
  # Permissions for CertificateSigningRequests
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["list", "watch", "create", "get", "update"]
  # Permissions for CFMTLSIssuer and CFMTLSClusterIssuer
  - apiGroups: ["cfmtls.cert.manager.io"]
    resources: ["cfmtlsissuers", "cfmtlsclusterissuers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cfmtls.cert.manager.io"]
    resources: ["cfmtlsissuers/status", "cfmtlsclusterissuers/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["cfmtls.cert.manager.io"]
    resources: ["cfmtlsissuers/conditions", "cfmtlsclusterissuers/conditions"]
    verbs: ["update", "patch"]
  # Permissions for Secrets and Events
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["list", "watch", "create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cfmtls-issuer.fullname" . }}-binding
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cfmtls-issuer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cfmtls-issuer.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
