apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cfmtls-issuer.serviceAccountName" . }}
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cfmtls-issuer.fullname" . }}-role
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificatesigningrequests", "certificaterequests", "certificaterequests/status"]
  verbs: ["list", "watch", "create", "get", "update", "patch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["list", "watch", "create", "get", "update"]
- apiGroups: ["cfmtls.cert.manager.io"]
  resources: ["*"]
  verbs: ["list", "watch", "create", "get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs: ["list", "watch", "create", "get", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cfmtls-issuer.fullname" . }}-binding
  labels:
    {{- include "cfmtls-issuer.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cfmtls-issuer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cfmtls-issuer.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io