# permissions to approve all sample-issuer.example.com requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:sample-issuer-example-com
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - CFMTLSIssuers.sample-issuer.example.com/*
  - CFMTLSClusterIssuers.sample-issuer.example.com/*
