# permissions to approve all mtls-issuer.cfl requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:mtls-issuer.cfl
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - CFMTLSIssuers.mtls-issuer.cfl/*
  - CFMTLSClusterIssuers.mtls-issuer.cfl/*
