---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - CFMTLSClusterIssuers.mtls-issuer.cfl/*
  - CFMTLSIssuers.mtls-issuer.cfl/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - mtls-issuer.cfl
  resources:
  - CFMTLSClusterIssuers
  - CFMTLSIssuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mtls-issuer.cfl
  resources:
  - CFMTLSClusterIssuers/status
  - CFMTLSIssuers/status
  verbs:
  - patch
