# This rule is not used by the project sample-external-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cfmtls.cert.manager.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: CFMTLSClusterIssuer-editor-role
rules:
- apiGroups:
  - cfmtls.cert.manager.io
  resources:
  - CFMTLSClusterIssuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cfmtls.cert.manager.io
  resources:
  - CFMTLSClusterIssuers/status
  verbs:
  - get
