# This rule is not used by the project sample-external-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mtls-issuer.cfl.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: CFMTLSIssuer-admin-role
rules:
- apiGroups:
  - mtls-issuer.cfl
  resources:
  - CFMTLSIssuers
  verbs:
  - '*'
- apiGroups:
  - mtls-issuer.cfl
  resources:
  - CFMTLSIssuers/status
  verbs:
  - get
