apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-CFMTLSClusterIssuer
spec:
  commonName: certificate-by-CFMTLSClusterIssuer.example.com
  secretName: certificate-by-CFMTLSClusterIssuer
  issuerRef:
    name: CFMTLSClusterIssuer-sample
    group: sample-issuer.example.com
    kind: CFMTLSClusterIssuer
