apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-CFMTLSIssuer
spec:
  commonName: certificate-by-CFMTLSIssuer.example.com
  secretName: certificate-by-CFMTLSIssuer
  issuerRef:
    name: CFMTLSIssuer-sample
    group: cfmtls.cert.manager.io
    kind: CFMTLSIssuer
