apiVersion: cfmtls.cert.manager.io/v1alpha1
kind: CFMTLSClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: sample-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: CFMTLSClusterIssuer-sample
spec:
  authSecretName: "CFMTLSClusterIssuer-sample-credentials"
  url: "http://cfmtls.cert.manager.io/api/v1"
