apiVersion: cfmtls.cert.manager.io/v1alpha1
kind: CFMTLSIssuer
metadata:
  labels:
    app.kubernetes.io/name: sample-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: CFMTLSIssuer-sample
spec:
  authSecretName: "CFMTLSIssuer-sample-credentials"
  url: "http://cfmtls.cert.manager.io/api/v1"
